name = "Task Force Prometheus"
author = "Task Force Prometheus Team"
prefix = "tfp"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "README*.md",
    "LICENSE",
    "logo_tfp.paa",
    "meta.cpp",
]

[lints.sqf.var_all_caps]
options.ignore = [
    "ACE_RECOMPILES",
]

[hemtt.launch.default]
workshop = [
    "450814997",  # CBA_A3
    "463939057",  # ace
    "2020940806", # KAT Advanced Medical
    "751965892",  # ACRE2

    # Weapons & Assets
    "843577117",  # RHSUSAF
    "843425103",  # RHSAFRF
    "2268351256", # Tier One Weapons

    # Gear
    "1795825073", # USP Gear - AIO
]
mission = "editor.vr"

[hemtt.launch.modpack]
extends = "default"
presets = ["tfpv1"]
