name = "Task Force Prometheus"
author = "Task Force Prometheus Team"
prefix = "tfp"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "README*.md",
    "LICENSE",
    "logo_tfp.paa",
    "meta.cpp",
]

[hemtt.launch.default]
workshop = [
    "450814997",  # CBA_A3
    "823636749",  # VSM All-In-One Collection
    "463939057",  # ace
    "2020940806", # KAT Advanced Medical
    "843577117",  # RHSUSAF
    "751965892",  # ACRE2
    "1875281645", # ILBE Assault Pack
    "2268351256", # Tier One Weapons
    "893349825",  # 3CB BAF Vehicles
]

[hemtt.launch.editor]
extends = "default"
mission = "editor.vr"
