name = "Task Force Prometheus"
author = "Task Force Prometheus Team"
prefix = "tfp"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "README*.md",
    "LICENSE",
    "logo_tfp.paa",
    "meta.cpp",
]

[lints.sqf.var_all_caps]
options.ignore = [
    "ACE_RECOMPILES",
]

[hemtt.launch.default]
workshop = [
    "450814997",  # CBA_A3
    "463939057",  # ace
    "2020940806", # KAT Advanced Medical
    "751965892",  # ACRE2

    # Weapons & Assets
    "843577117",  # RHSUSAF
    "843425103",  # RHSAFRF
    "2268351256", # Tier One Weapons
    "893349825",  # 3CB BAF Vehicles

    # Gear
    "1870770453", # Ultimate Flag Patches - UFP
    "2044374502", # USP Gear - Core
    "2049719091", # USP Gear - NVG
    "2113786615", # USP Gear - Backpacks
    "2056229605", # USP Gear - ACE
    "2365500050", # USP Gear - Uniforms
    "2588603554", # USP Gear - IHPS
]

[hemtt.launch.editor]
extends = "default"
mission = "editor.vr"
